version: '2'
services:
  postgres:
    image: postgres:9.6
    volumes:
    - ./runtime/postgres:/var/lib/postgresql/data:Z
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=qwerty
  redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - ./runtime/redis:/data:Z
  nginx:
    image: nginx
    network_mode: "host"
    volumes:
    - ./dockerizing/nginx/configs/default.conf:/etc/nginx/conf.d/default.conf:Z
    - ./runtime/logs/:/var/log/nginx/:Z
